fix src/script/readsb/uiLMapControls.ts:215:30 - error TS2352: Conversion of type 'HTMLAnchorElement' to type 'HTMLLinkElement' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.   Type 'HTMLAnchorElement' is missing the following properties from type 'HTMLLinkElement': as, crossOrigin, disabled, imageSizes, and 5 more.
215                 const link = L.DomUtil.create("a", className + "-toggle", container) as HTMLLinkElement;
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error.